spring:
  datasource:
    url: jdbc:mysql://116.205.142.103:3306/labor_manage?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ZMxT5dzhZk4DFhYT
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
server:
  port: 8808
  servlet:
    context-path: /labor

#文件根目录地址
attachRootPath: "/labormanagement/upload"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
